### ISSUE TITLE
Concurrent clients clearing others subscriptions

### ISSUE THREAD

**Issue by HerveZu** [GimliCZ/TwitchEventSub_Websocket#13]
My application is running multiple instances at the same time to insure redundancy. The issue is that when a new instance starts it  clears all existing subscriptions which prevent the other instances from listening to Twitch events. 
Ideally I'd like to have the clients to only clear the inactive subscriptions, leaving the active ones (currently in use by other instances)

**Comment by GimliCZ** [comment]
This aplication strictly adheres to twitch documentation. Creation of additional websockets and instances for same user for "redundancy" purposes is out of question. Only thing I can offer is extension for DI.

**Comment by HerveZu** [comment]
Would it be possible to integrate conduits ? (https://dev.twitch.tv/docs/eventsub/handling-conduit-events/)
So then we could link websocket connections to shards and therefore maintain multiple shards. I would need to know when a session get created (to link it to a shard) and have an option to not automatically remove subscriptions

**Comment by GimliCZ** [comment]
In the foreseeable future, probably yes.
Will it be within next two months. Probably not.

**Comment by HerveZu** [comment]
Could you add some option to disable automatic subscription and an event handler for the welcome message so I can implement the conduit subscription myself ?

**Comment by GimliCZ** [comment]
I have been thinking about it for quite some time. 
I think that it would be a best to create entire new branch and try to restructurize project for conduit purposes.
Current websocket / session solution is good enough for "simple" comunication, but if we want to have redundancies and shards
It would be needed to make some drastic changes in sub manager and potencialy create conduit handler with concurent websockets.
I will make some digging and try to enable forking since I dont see reason why it should be blocked at first place.
I will try to make changes this week.

**Comment by GimliCZ** [comment]
You can try to fork the Conduit-Websocket branch.

**Comment by GimliCZ** [comment]
Rework of library in testing phase. 
Next will be implementation of conduits. 
Closing issue.
